// Barrel del design system: única interfaz pública (D3/D4).
export { AreaTexto } from './gotas/AreaTexto';
export { Boton } from './gotas/Boton';
export { CampoClave } from './gotas/CampoClave';
export { CampoSelect } from './gotas/CampoSelect';
export type { OpcionSelect } from './gotas/CampoSelect';
export { CampoTexto } from './gotas/CampoTexto';
export { Chip } from './gotas/Chip';
export { Metrica } from './gotas/Metrica';
export { TablaMini } from './gotas/TablaMini';
export { Tarjeta } from './gotas/Tarjeta';
export { FormAcceso } from './corrientes/FormAcceso';
export { FormBloque } from './corrientes/FormBloque';
export { FormUsuario } from './corrientes/FormUsuario';
export type { OpcionRol } from './corrientes/FormUsuario';
export { ListaMetricas } from './corrientes/ListaMetricas';
export type { ItemMetrica } from './corrientes/ListaMetricas';
export { PanelDetalleNodo } from './corrientes/PanelDetalleNodo';
export type { VecinoPanel } from './corrientes/PanelDetalleNodo';
export { PanelFiltro } from './corrientes/PanelFiltro';
export { TablaPadron } from './corrientes/TablaPadron';
export type { FilaPadron } from './corrientes/TablaPadron';
export { EncabezadoApp } from './cauces/EncabezadoApp';
export { NavegacionInferior } from './cauces/NavegacionInferior';
export { NavegacionLateral } from './cauces/NavegacionLateral';
export { PanelAcceso } from './cauces/PanelAcceso';
